version: '3'

services:
  # pushgateway
  pushgateway:
    image: prom/pushgateway
    container_name: pushgateway
    restart: always
    ports:
      - 9091:9091
    networks:
      - prometheus
      
networks:
  prometheus:
    driver: bridge